apiVersion: certification.redhat.com/v1alpha1
kind: OperatorPipeline
metadata:
  name: operatorpipeline-sample
  namespace: oco
spec:
  operatorPipelinesRelease: main
  kubeconfigSecretName: "kubeconfig"
  gitHubSecretName: "github-api-token"
  pyxisSecretName: "pyxis-api-secret"
  applyCIPipeline: true
  applyHostedPipeline: false
  applyReleasePipeline: false
