name: Build Main

on:
  push:
    branches: [ main ]

jobs:
  build-main:
    name: Build and push a main snapshot image
    runs-on: ubuntu-18.04
    env:
      IMAGE_REGISTRY: quay.io/opdev
    steps:
    - uses: actions/checkout@v2
    - name: Fetch latest release version
      uses: reloc8/action-latest-release-version@1.0.0
      id: fetch-latest-release
    - name: Set Env Tags
      run: echo RELEASE_TAG=${{ steps.fetch-latest-release.outputs.latest-release }} >> $GITHUB_ENV
    - name: Set a default if release tag is empty
      if: ${{ steps.fetch-latest-release.outputs.latest-release }} == ""
      run: echo RELEASE_TAG=0.0.0 >> $GITHUB_ENV

    - name: Build Operator Image
      id: build-operator-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_REGISTRY }}/operator-certification-operator
        tags: ${{ github.sha }}
        build-args: |
          quay_expiration=1w
          release_tag=${{ env.RELEASE_TAG }}-alpha
        dockerfiles: |
          ./Dockerfile

    - name: Build Bundle Image
      id: build-bundle-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_REGISTRY }}/operator-certification-operator-bundle
        tags: ${{ github.sha }}
        build-args: |
          quay_expiration=1w
          release_tag=${{ env.RELEASE_TAG }}-alpha
        dockerfiles: |
          ./bundle.Dockerfile

    - name: Push Operator Image
      id: push-operator-image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: operator-certification-operator
        tags: ${{ steps.build-operator-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Push Bundle Image
      id: push-bundle-image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: operator-certification-operator-bundle
        tags: ${{ steps.build-bundle-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: echo "Operator Image pushed to ${{ steps.push-operator-image.outputs.registry-paths }}"
    - run: echo "Bundle Image pushed to ${{ steps.push-bundle-image.outputs.registry-paths }}"
